### ISSUE TITLE
Code issue when calling bitsocket.connect

### ISSUE THREAD

**Issue by bloodchen** [jonaird/planariette#2]
The timestamp property of the query shall be deleted, otherwise, no new tx will come.
if (listenMode == true) {
        delete newQuery.q.find.timestamp // add this one
        bitsocket.connect(newQuery, processFunc,null, useBOB ? 'https://bob.bitsocket.network/s/' : null)
    }

**Comment by jonaird** [comment]
Could you describe the problem? You're not getting new tx? Is this a new problem that suddenly happened?

If it is for a specific query also provide it.

**Comment by bloodchen** [comment]
I did another test, it seems it doesn't matter.

**Comment by bloodchen** [comment]
With more tests, it does increase the success rate by adding "delete newQuery.q.find.timestamp // add this one" this line.
Since it does no harm, I suggest to add this line in the code.

**Comment by jonaird** [comment]
Ok could you send a pull request?

**Comment by bloodchen** [comment]
Sure. Can you add me to the members of the project?

**Comment by bloodchen** [comment]
or you can make the changes, it's an one line change in index.js
if (listenMode == true) {
        delete newQuery.q.find.timestamp //add this line
        bitsocket.connect(newQuery, processFunc,null, useBOB ? 'https://bob.bitsocket.network/s/' : null)
    }

**Comment by jonaird** [comment]
ok. a bit busy I'll get to this when I can.

**Comment by jonaird** [comment]
Ok, should be changed. Next time you can use this process to submit a change: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
